"""Strong-generator gold-critic step. After the weak arms run (SELF/FUSED/AXES/
MAD, 1 round) from a SHARED r0 generated by Qwen3.6-35B-A3B, this revises the
SAME r0 using hand-written gold critiques (critic = Opus) in three structures:
  goldfused (holistic), goldaxes (per-axis), goldmad (per-axis + debate).
Weak r1 (Qwen3.6 as its own critic) already exists per arm. Judge = Fable, later.
Produces results/strongen/gold/{task}/r1_{variant}.{html,png}.
"""
from __future__ import annotations
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import argparse, asyncio, glob, json, os, time
from types import SimpleNamespace
from src.infra.client import make_client, BudgetedUsage
from src.infra.render import render_and_probe
from src.arms.common import gen_revision

RUN = "results/strongen"
VARIANTS = {"goldfused": "_critiques_goldfused",
            "goldaxes":  "_critiques_goldaxes",
            "goldmad":   "_critiques_goldmad"}


def instruction_for(task):
    for arm in ("MAD", "AXES", "FUSED", "SELF"):
        p = f"{RUN}/s0/{arm}/problems/{task}/trace.json"
        if os.path.exists(p):
            return json.load(open(p))["instruction"]
    raise FileNotFoundError(f"no trace for {task}")


async def one_unit(task, variant, gen_c, cfg, usage):
    d = f"{RUN}/gold/{task}"; os.makedirs(d, exist_ok=True)
    r0_html = open(f"{RUN}/r0_pool/s0/{task}/r0.html").read()
    instruction = instruction_for(task)
    critique = open(f"{RUN}/{VARIANTS[variant]}/{task}.txt").read().strip()
    print(f"[{task}/{variant}] revising r0 ({len(critique)} chars)...", flush=True)
    html = await gen_revision(instruction, r0_html, critique, gen_c, cfg, usage)
    open(f"{d}/r1_{variant}.html", "w").write(html)
    info = await render_and_probe(html, f"{d}/r1_{variant}.png", n_shots=3)
    json.dump({"task": task, "variant": variant, "critique_chars": len(critique),
               "bytes": len(html.encode()), "probe": info},
              open(f"{d}/r1_{variant}_meta.json", "w"), indent=1)
    print(f"[{task}/{variant}] DONE rendered={info.get('rendered')}", flush=True)
    return (task, variant), info.get("rendered")


async def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gen-ports", default="8000,8001")
    ap.add_argument("--gen-model", required=True)
    ap.add_argument("--max-tokens", type=int, default=16384)
    ap.add_argument("--concurrency", type=int, default=8)
    ap.add_argument("--wait-min", type=int, default=180)
    ap.add_argument("--only", default="",
                    help="comma-sep task/variant pairs to (re)generate, e.g. ab000003/goldaxes,ab000003/goldfused")
    args = ap.parse_args()

    tasks = sorted(os.path.basename(os.path.dirname(p))
                   for p in glob.glob(f"{RUN}/r0_pool/s0/*/r0.html"))
    if args.only:
        units = [tuple(p.split("/")) for p in args.only.split(",") if p.strip()]
    else:
        units = [(t, v) for t in tasks for v in VARIANTS]
    print(f"tasks={len(tasks)} variants={list(VARIANTS)} units={len(units)}", flush=True)
    ports = [int(p) for p in args.gen_ports.split(",")]
    gen_c = make_client(ports, args.gen_model, args.concurrency, False, "gen")
    cfg = SimpleNamespace(max_tokens=args.max_tokens, gen_temperature=0.7)
    usage = BudgetedUsage(50_000_000)

    async with gen_c:  # open the aiohttp session (was missing -> all gens returned None)
        done, deadline = set(), time.time() + args.wait_min * 60
        while len(done) < len(units) and time.time() < deadline:
            ready = [(t, v) for (t, v) in units if (t, v) not in done
                     and os.path.exists(f"{RUN}/{VARIANTS[v]}/{t}.txt")]
            if not ready:
                await asyncio.sleep(15); continue
            res = await asyncio.gather(*(one_unit(t, v, gen_c, cfg, usage) for (t, v) in ready),
                                       return_exceptions=True)
            for r in res:
                if isinstance(r, tuple): done.add(r[0])
                else: print(f"ERROR: {r}", flush=True)
            print(f"progress {len(done)}/{len(units)}", flush=True)
    print(f"FINISHED {len(done)}/{len(units)}", flush=True)


if __name__ == "__main__":
    asyncio.run(main())
